CREATE TABLE [dbo].[Consumer](
	[No] [int] IDENTITY(1,1) NOT NULL,
	[Name1] [nvarchar](50) NULL,
	[Name2] [nvarchar](50) NOT NULL,
	[Flag] [tinyint] NOT NULL,
	[Age] [int] NULL,
 CONSTRAINT [pk_Consumer_No] PRIMARY KEY CLUSTERED 
(
	[No] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
